pull_request_rules:
  - name: Automatic merge for steward
    conditions:
      - and:
        - 'author=BottyMcBotBot'
        - "check-success~=test"
    actions:
      merge:
        method: merge
